backend:
  name: git-gateway
  branch: main
  identity_url: "https://anomaholdings.com/.netlify/identity"
  gateway_url: "https://anomaholdings.com/.netlify/git"

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "summary", widget: "text", hint: "A short description shown on the blog listing page" }
      - { label: "Body", name: "body", widget: "markdown" }
